import type { TemplateDocument, TemplateElement } from "./templateTypes";

type TemplateElementSeed = Omit<TemplateElement, "revisions">;

const zeroRevisions = {
  base: 0,
  desktop: 0,
  tablet: 0,
  mobile: 0,
};

const elementSeeds: TemplateElementSeed[] = [
  {
    id: "page-root",
    type: "page",
    name: "Page",
    children: [
      "top-nav",
      "hero-section",
      "stats-section",
      "features-section",
      "process-section",
      "cta-section",
      "footer-section",
    ],
    content: {},
    style: { background: "#f7f4ee", color: "#17202a" },
    layout: { variant: "page" },
    overrides: {},
  },
  {
    id: "top-nav",
    type: "nav",
    name: "Top Nav",
    parentId: "page-root",
    children: [],
    content: { text: "Northstar Studio" },
    style: { background: "rgba(247, 244, 238, 0.92)", borderColor: "#ded6c9" },
    layout: { variant: "top-nav", padding: "18px 40px" },
    overrides: { mobile: { layout: { padding: "16px 22px" } } },
  },
  {
    id: "hero-section",
    type: "section",
    name: "Hero",
    parentId: "page-root",
    children: [
      "hero-copy-stack",
      "hero-visual-card",
    ],
    content: {},
    style: { background: "#f7f4ee" },
    layout: {
      columns: 2,
      gap: "36px",
      maxWidth: "1120px",
      padding: "82px 40px 70px",
      variant: "hero",
    },
    overrides: {
      tablet: { layout: { columns: 1, padding: "70px 34px 58px" } },
      mobile: { layout: { columns: 1, padding: "48px 22px 42px" } },
    },
  },
  {
    id: "hero-copy-stack",
    type: "stack",
    name: "Hero Copy",
    parentId: "hero-section",
    children: [
      "hero-eyebrow",
      "hero-heading",
      "hero-body",
      "hero-actions",
    ],
    content: {},
    style: {},
    layout: { gap: "20px", variant: "hero-copy" },
    overrides: {},
  },
  {
    id: "hero-eyebrow",
    type: "badge",
    name: "Hero Eyebrow",
    parentId: "hero-copy-stack",
    children: [],
    content: { text: "AI-assisted launch systems" },
    style: { background: "#e6eee9", color: "#1e5b52", tone: "accent" },
    layout: { variant: "eyebrow" },
    overrides: {},
  },
  {
    id: "hero-heading",
    type: "text",
    name: "Hero Heading",
    parentId: "hero-copy-stack",
    children: [],
    content: {
      role: "heading1",
      text: "Premium websites for teams moving faster than their roadmap.",
    },
    style: { color: "#152028" },
    layout: { variant: "hero-heading" },
    overrides: {
      mobile: {
        content: {
          text: "Premium websites for fast-moving teams.",
        },
        layout: { variant: "hero-heading compact" },
      },
    },
  },
  {
    id: "hero-body",
    type: "text",
    name: "Hero Body",
    parentId: "hero-copy-stack",
    children: [],
    content: {
      role: "paragraph",
      text: "Northstar Studio designs launch-ready web systems with sharp positioning, responsive components, and calm operational handoff.",
    },
    style: { color: "#53606b" },
    layout: { variant: "lead" },
    overrides: {},
  },
  {
    id: "hero-actions",
    type: "container",
    name: "Hero Actions",
    parentId: "hero-copy-stack",
    children: ["hero-primary-cta", "hero-secondary-cta"],
    content: {},
    style: {},
    layout: { gap: "12px", variant: "actions" },
    overrides: { mobile: { layout: { variant: "actions stacked" } } },
  },
  {
    id: "hero-primary-cta",
    type: "button",
    name: "Hero Primary CTA",
    parentId: "hero-actions",
    children: [],
    content: { href: "#cta-section", text: "Plan my launch" },
    style: { background: "#1f5f55", color: "#ffffff", tone: "accent" },
    layout: { variant: "primary-button" },
    overrides: {},
  },
  {
    id: "hero-secondary-cta",
    type: "button",
    name: "Hero Secondary CTA",
    parentId: "hero-actions",
    children: [],
    content: { href: "#process-section", text: "See process" },
    style: { background: "#ffffff", color: "#24313b", borderColor: "#d8d0c2" },
    layout: { variant: "secondary-button" },
    overrides: {},
  },
  {
    id: "hero-visual-card",
    type: "card",
    name: "Hero Visual Card",
    parentId: "hero-section",
    children: ["hero-visual-badge", "hero-visual-title", "hero-visual-body"],
    content: {},
    style: {
      background: "#17202a",
      color: "#f6f0e7",
      radius: "26px",
      shadow: "0 24px 60px rgba(23, 32, 42, 0.24)",
    },
    layout: { padding: "30px", variant: "hero-visual" },
    overrides: { mobile: { layout: { padding: "24px" } } },
  },
  {
    id: "hero-visual-badge",
    type: "badge",
    name: "Visual Badge",
    parentId: "hero-visual-card",
    children: [],
    content: { text: "Launch map" },
    style: { background: "#f0c36b", color: "#17202a", tone: "accent" },
    layout: { variant: "eyebrow" },
    overrides: {},
  },
  {
    id: "hero-visual-title",
    type: "text",
    name: "Visual Title",
    parentId: "hero-visual-card",
    children: [],
    content: { role: "heading2", text: "Strategy, design, and automation in one clean sprint." },
    style: { color: "#fff7eb" },
    layout: { variant: "card-title" },
    overrides: {},
  },
  {
    id: "hero-visual-body",
    type: "text",
    name: "Visual Body",
    parentId: "hero-visual-card",
    children: [],
    content: {
      role: "paragraph",
      text: "A single source of truth keeps message, layout, and launch assets aligned across every viewport.",
    },
    style: { color: "#cad3d7" },
    layout: { variant: "card-body" },
    overrides: {},
  },
  {
    id: "stats-section",
    type: "section",
    name: "Stats",
    parentId: "page-root",
    children: ["stat-conversion", "stat-launches", "stat-satisfaction"],
    content: {},
    style: { background: "#ffffff", borderColor: "#e4ddd2" },
    layout: { columns: 3, gap: "18px", maxWidth: "1120px", padding: "34px 40px", variant: "stats" },
    overrides: {
      mobile: { layout: { columns: 1, padding: "28px 22px" } },
    },
  },
  {
    id: "stat-conversion",
    type: "stat",
    name: "Conversion Stat",
    parentId: "stats-section",
    children: [],
    content: { label: "average lift", text: "38%" },
    style: {},
    layout: { variant: "stat" },
    overrides: {},
  },
  {
    id: "stat-launches",
    type: "stat",
    name: "Launches Stat",
    parentId: "stats-section",
    children: [],
    content: { label: "launch systems", text: "52" },
    style: {},
    layout: { variant: "stat" },
    overrides: {},
  },
  {
    id: "stat-satisfaction",
    type: "stat",
    name: "Satisfaction Stat",
    parentId: "stats-section",
    children: [],
    content: { label: "handoff clarity", text: "96%" },
    style: {},
    layout: { variant: "stat" },
    overrides: {},
  },
  {
    id: "features-section",
    type: "section",
    name: "Features",
    parentId: "page-root",
    children: ["features-heading", "feature-strategy", "feature-design", "feature-automation"],
    content: {},
    style: { background: "#f7f4ee" },
    layout: { columns: 3, gap: "18px", maxWidth: "1120px", padding: "72px 40px", variant: "feature-grid" },
    overrides: {
      tablet: { layout: { columns: 2 } },
      mobile: { layout: { columns: 1, padding: "50px 22px" } },
    },
  },
  {
    id: "features-heading",
    type: "text",
    name: "Features Heading",
    parentId: "features-section",
    children: [],
    content: { role: "heading2", text: "Built for clean launches, not endless revisions." },
    style: { color: "#17202a" },
    layout: { variant: "section-heading" },
    overrides: {},
  },
  {
    id: "feature-strategy",
    type: "card",
    name: "Feature Strategy",
    parentId: "features-section",
    children: ["feature-strategy-title", "feature-strategy-body"],
    content: {},
    style: { background: "#ffffff", borderColor: "#e2dbcf", radius: "18px" },
    layout: { padding: "24px", variant: "feature-card" },
    overrides: {},
  },
  {
    id: "feature-strategy-title",
    type: "text",
    name: "Strategy Title",
    parentId: "feature-strategy",
    children: [],
    content: { role: "heading3", text: "Positioning sprint" },
    style: {},
    layout: { variant: "card-title" },
    overrides: {},
  },
  {
    id: "feature-strategy-body",
    type: "text",
    name: "Strategy Body",
    parentId: "feature-strategy",
    children: [],
    content: { role: "paragraph", text: "Clarify the promise, audience, and conversion path before a pixel moves." },
    style: { color: "#5d6872" },
    layout: { variant: "card-body" },
    overrides: {},
  },
  {
    id: "feature-design",
    type: "card",
    name: "Feature Design",
    parentId: "features-section",
    children: ["feature-design-title", "feature-design-body"],
    content: {},
    style: { background: "#ffffff", borderColor: "#e2dbcf", radius: "18px" },
    layout: { padding: "24px", variant: "feature-card" },
    overrides: {},
  },
  {
    id: "feature-design-title",
    type: "text",
    name: "Design Title",
    parentId: "feature-design",
    children: [],
    content: { role: "heading3", text: "Responsive system" },
    style: {},
    layout: { variant: "card-title" },
    overrides: {},
  },
  {
    id: "feature-design-body",
    type: "text",
    name: "Design Body",
    parentId: "feature-design",
    children: [],
    content: { role: "paragraph", text: "Every section is shaped for desktop, tablet, and mobile from the same source." },
    style: { color: "#5d6872" },
    layout: { variant: "card-body" },
    overrides: {},
  },
  {
    id: "feature-automation",
    type: "card",
    name: "Feature Automation",
    parentId: "features-section",
    children: ["feature-automation-title", "feature-automation-body"],
    content: {},
    style: { background: "#ffffff", borderColor: "#e2dbcf", radius: "18px" },
    layout: { padding: "24px", variant: "feature-card" },
    overrides: {},
  },
  {
    id: "feature-automation-title",
    type: "text",
    name: "Automation Title",
    parentId: "feature-automation",
    children: [],
    content: { role: "heading3", text: "Launch handoff" },
    style: {},
    layout: { variant: "card-title" },
    overrides: {},
  },
  {
    id: "feature-automation-body",
    type: "text",
    name: "Automation Body",
    parentId: "feature-automation",
    children: [],
    content: { role: "paragraph", text: "Documentation and component rules make the site easier to extend after launch." },
    style: { color: "#5d6872" },
    layout: { variant: "card-body" },
    overrides: {},
  },
  {
    id: "process-section",
    type: "section",
    name: "Process",
    parentId: "page-root",
    children: ["process-heading", "process-discover", "process-build", "process-launch"],
    content: {},
    style: { background: "#17202a", color: "#f8f3ea" },
    layout: { columns: 3, gap: "18px", maxWidth: "1120px", padding: "72px 40px", variant: "process" },
    overrides: { mobile: { layout: { columns: 1, padding: "54px 22px" } } },
  },
  {
    id: "process-heading",
    type: "text",
    name: "Process Heading",
    parentId: "process-section",
    children: [],
    content: { role: "heading2", text: "A launch process with less noise." },
    style: { color: "#fff7eb" },
    layout: { variant: "section-heading" },
    overrides: {},
  },
  {
    id: "process-discover",
    type: "card",
    name: "Process Discover",
    parentId: "process-section",
    children: ["process-discover-title", "process-discover-body"],
    content: {},
    style: { background: "#22303b", borderColor: "#344552", radius: "18px" },
    layout: { padding: "22px", variant: "process-card" },
    overrides: {},
  },
  {
    id: "process-discover-title",
    type: "text",
    name: "Discover Title",
    parentId: "process-discover",
    children: [],
    content: { role: "heading3", text: "01 Discover" },
    style: { color: "#f0c36b" },
    layout: { variant: "card-title" },
    overrides: {},
  },
  {
    id: "process-discover-body",
    type: "text",
    name: "Discover Body",
    parentId: "process-discover",
    children: [],
    content: { role: "paragraph", text: "Map goals, audiences, and the smallest complete launch story." },
    style: { color: "#d9e0e2" },
    layout: { variant: "card-body" },
    overrides: {},
  },
  {
    id: "process-build",
    type: "card",
    name: "Process Build",
    parentId: "process-section",
    children: ["process-build-title", "process-build-body"],
    content: {},
    style: { background: "#22303b", borderColor: "#344552", radius: "18px" },
    layout: { padding: "22px", variant: "process-card" },
    overrides: {},
  },
  {
    id: "process-build-title",
    type: "text",
    name: "Build Title",
    parentId: "process-build",
    children: [],
    content: { role: "heading3", text: "02 Build" },
    style: { color: "#f0c36b" },
    layout: { variant: "card-title" },
    overrides: {},
  },
  {
    id: "process-build-body",
    type: "text",
    name: "Build Body",
    parentId: "process-build",
    children: [],
    content: { role: "paragraph", text: "Turn the model into responsive sections and reviewable decisions." },
    style: { color: "#d9e0e2" },
    layout: { variant: "card-body" },
    overrides: {},
  },
  {
    id: "process-launch",
    type: "card",
    name: "Process Launch",
    parentId: "process-section",
    children: ["process-launch-title", "process-launch-body"],
    content: {},
    style: { background: "#22303b", borderColor: "#344552", radius: "18px" },
    layout: { padding: "22px", variant: "process-card" },
    overrides: {},
  },
  {
    id: "process-launch-title",
    type: "text",
    name: "Launch Title",
    parentId: "process-launch",
    children: [],
    content: { role: "heading3", text: "03 Launch" },
    style: { color: "#f0c36b" },
    layout: { variant: "card-title" },
    overrides: {},
  },
  {
    id: "process-launch-body",
    type: "text",
    name: "Launch Body",
    parentId: "process-launch",
    children: [],
    content: { role: "paragraph", text: "Ship with a stable source of truth and clear next-edit boundaries." },
    style: { color: "#d9e0e2" },
    layout: { variant: "card-body" },
    overrides: {},
  },
  {
    id: "cta-section",
    type: "section",
    name: "Call To Action",
    parentId: "page-root",
    children: ["cta-heading", "cta-body", "cta-button"],
    content: {},
    style: { background: "#e9efe9" },
    layout: { maxWidth: "1120px", padding: "74px 40px", variant: "cta" },
    overrides: { mobile: { layout: { padding: "52px 22px" } } },
  },
  {
    id: "cta-heading",
    type: "text",
    name: "CTA Heading",
    parentId: "cta-section",
    children: [],
    content: { role: "heading2", text: "Give your next launch a reliable center." },
    style: { color: "#17202a", textAlign: "center" },
    layout: { variant: "cta-heading" },
    overrides: {},
  },
  {
    id: "cta-body",
    type: "text",
    name: "CTA Body",
    parentId: "cta-section",
    children: [],
    content: { role: "paragraph", text: "Start with one canonical template model, then let future scoped AI edits propose changes safely." },
    style: { color: "#53606b", textAlign: "center" },
    layout: { variant: "lead centered" },
    overrides: {},
  },
  {
    id: "cta-button",
    type: "button",
    name: "CTA Button",
    parentId: "cta-section",
    children: [],
    content: { href: "mailto:hello@northstar.example", text: "Start the sprint" },
    style: { background: "#1f5f55", color: "#ffffff", tone: "accent" },
    layout: { variant: "primary-button centered" },
    overrides: {},
  },
  {
    id: "footer-section",
    type: "section",
    name: "Footer",
    parentId: "page-root",
    children: ["footer-copy"],
    content: {},
    style: { background: "#111820", color: "#dfe7e9" },
    layout: { maxWidth: "1120px", padding: "28px 40px", variant: "footer" },
    overrides: { mobile: { layout: { padding: "26px 22px" } } },
  },
  {
    id: "footer-copy",
    type: "text",
    name: "Footer Copy",
    parentId: "footer-section",
    children: [],
    content: { role: "paragraph", text: "Northstar Studio - original template for the Scoped AI Template Editor assignment." },
    style: { color: "#dfe7e9", textAlign: "center" },
    layout: { variant: "footer-copy" },
    overrides: {},
  },
];

export const northstarTemplate: TemplateDocument = {
  metadata: {
    schemaVersion: 2,
    templateId: "northstar-studio-v1",
    templateName: "Northstar Studio",
    source: "original",
    status: "renderable",
  },
  rootElementId: "page-root",
  elements: Object.fromEntries(
    elementSeeds.map((element) => [
      element.id,
      {
        ...element,
        revisions: { ...zeroRevisions },
      },
    ]),
  ),
  viewportSettings: {
    desktop: { label: "Desktop", width: 1440 },
    tablet: { label: "Tablet", width: 768 },
    mobile: { label: "Mobile", width: 375 },
  },
};
